default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: flake8
        additional_dependencies:
        -  flake8-bugbear
        -  flake8-colors
        -  flake8-docstrings
        -  flake8-import-order
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: python -m pylint.__main__
        language: system
        types: [python]
        exclude: >
            (?x)^(
                bin/.*|
                docs/.*
            )$

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
